<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post list item template
 *
 * @var $block \Magefan\Blog\Block\Post\AbstractPost
 */
?>
<?php
    $_post = $this->getPost();
    $_postUrl = $block->escapeUrl($_post->getPostUrl());
    $_postName = $block->escapeHtml($_post->getTitle());
    $_postDate = $_post->getData("publish_time");
?>
<li class="post-holder post-holder-<?= $block->escapeHtml($_post->getId()) ?>">
    <div class="post-banner no-banner"></div>
    <?php if ($_post->isPublishDateEnabled()) { ?>
        <div class="post-date">
            <span class="day"><?= $block->escapeHtml($_post->getPublishDate("j")); ?></span>
            <span class="month"><?= $block->escapeHtml($_post->getPublishDate("M")); ?></span>
        </div>
    <?php } ?>
    <div class="post-header">
        <div class="post-title-holder">
            <div class="addthis_toolbox addthis_default_style"
                 addthis:url="<?= /*@noEscape*/ $_postUrl ?>"">
                <a class="addthis_button_facebook"></a>
                <a class="addthis_button_twitter"></a>
                <a class="addthis_button_email"></a>
                <a class="addthis_button_compact"></a>
            </div>
            <h2 class="post-title">
                <a class="post-item-link"
                   href="<?= $block->escapeUrl($_postUrl) ?>">
                    <?= $block->escapeHtml($_postName); ?>
                </a>
            </h2>
        </div>
    </div>

    <div class="post-content">
        <div class="post-description clearfix">
            <?php $featuredImage = $_post->getFeaturedListImage() ?: $_post->getFeaturedImage(); ?>
            <?php if ($featuredImage) { ?>
                <?php
                $featuredImgAlt = $_post->getData('featured_list_img_alt') ?: $_post->getData('featured_img_alt');
                if (!$featuredImgAlt) {
                    $featuredImgAlt = $_postName;
                }
                ?>
                <div class="post-ftimg-hld">
                    <a href="<?= /*@noEscape*/ $_postUrl ?>" title="<?= /*@noEscape*/ $_postName ?>">
                        <img src="<?= $block->escapeUrl($featuredImage) ?>"
                             alt="<?= $block->escapeHtml($featuredImgAlt) ?>" />
                    </a>
                </div>
            <?php } ?>
            <div class="post-text-hld clearfix">
                <?= /*@noEscape*/ $block->getShorContent() ?>
            </div>

            <a class="post-read-more"
               href="<?= /*@noEscape*/ $_postUrl ?>"
               title="<?= /*@noEscape*/ $_postName ?>"
               >
                <?= $block->escapeHtml(__('Read more &#187;')) ?>
            </a>
        </div>
    </div>
    <div class="post-footer">
        <?= $block->getInfoHtml() ?>
    </div>
</li>